# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline on AoU

# Prerequisite
# list_of_plink_files: "plink_testing/afr_plink_file_list.txt"
# list_of_vcf_files: "plink_testing/afr_vcf_file_list.txt"
# list_of_model_files: "plink_testing/afr_model_file_list.txt"
# list_of_variance_ratio_files: "plink_testing/afr_variance_file_list.txt"
# sparse_matrix: "/home/jupyter/conditioning_test/afr/mtx/allofus_array_afr_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
# list_of_group_files: "plink_testing/afr_group_file_list.txt"
list_of_vcf_files: "aou_paths/sas_vcffiles.txt"
list_of_model_files: "aou_paths/sas_modelfiles.txt"
list_of_variance_ratio_files: "aou_paths/sas_variancefiles.txt"
sparse_matrix: "/home/jupyter/conditioning_test/sas/mtx/allofus_array_sas_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
list_of_group_files: "aou_paths/sas_groupfiles.txt"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "gene_pheno_test.csv"
gene_trait_pairs_to_test_with_conditioning_variants": "gene_phenotype_pairs_with_conditioning_variants.tsv"
protein_coding_region_bed: "data/protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "pilot_phenotypes.json"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2

# rule: prune
prune: true
p_thres: 0.01

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense,pLoF:damaging_missense"
use_null_var_ratio: false

# SAIGE versions for filetypes
saige_vcf_version: "1.3.6"
saige_plink_version: "1.3.6"
saige_pgen_version: "1.5.0"
