# Config File for BRaVa Pilot Study Common Variant Conditional Analysis Pipeline on AoU

# Prerequisite
list_of_vcf_files: "aou_paths/amr/amr_vcf_file_list.txt"
list_of_model_files: "aou_paths/amr/amr_model_file_list.txt"
list_of_variance_ratio_files: "aou_paths/amr/amr_variance_null_file_list.txt"
sparse_matrix: "snakemake_amr/mtx/allofus_array_amr_snp_wise_relatednessCutoff_0.05_5000_randomMarkersUsed.sparseGRM.mtx"
list_of_group_files: "aou_paths/amr/amr_group_file_list.txt"

## Prerequisite: Don't need to change if using files/instructions provided in repo 
gene_trait_pairs_to_test: "gene_pheno.csv"
protein_coding_region_bed: "protein_coding_regions_hg38_no_padding_no_UTR_v39.bed"
phenotype_json: "pilot_phenotypes.json"

# rule: id_variants_for_conditioning 
distance: 500000
maf:
  - 0.001
  - 0.0001
threads: 2

# rule: prune
prune: true
p_thres: 0.01

# rule: spa_tests_conditional
min_mac: 0.5
annotations_to_include: "pLoF,damaging_missense,other_missense,synonymous,pLoF:damaging_missense,pLoF:damaging_missense:other_missense:synonymous"
use_null_var_ratio: true
